import { IAnimeGenres } from '@interfaces/redux/animes.interface';

export const dataGenre: IAnimeGenres = [
  'Action',
  'Adventure',
  'Cars',
  'Comedy',
  'Dementia',
  'Demons',
  'Drama',
  // 'Dub',
  // 'Ecchi',
  'Family',
  'Fantasy',
  'Game',
  'Gourmet',
  // 'Harem',
  // 'Hentai',
  'Historical',
  'Horror',
  'Josei',
  'Kids',
  'Magic',
  'Martial arts',
  'Mecha',
  'Military',
  'Music',
  'Mystery',
  'Parody',
  'Police',
  'Psychological',
  'Romance',
  'Samurai',
  'School',
  'Sci-fi',
  'Seinen',
  'Shoujo',
  'Shoujo-ai',
  'Shounen',
  'Shounen-ai',
  'Slice-of-life',
  'Space',
  'Sports',
  'Super-power',
  'Supernatural',
  'Suspense',
  'Thriller'
];
